feat: add section solutions
sawala-tech/sawala.tech pull request #19
Opened 2022-08-24 06:29 UTC by Nunuyy

Description of PR that completes issue here...

## Changes

- Description of changes

## Screenshots

(prefer animated gif)

## Checklist

- [ ] Requires dependency update?
- [ ] Automated tests
- [ ] Looks good on large screens
- [ ] Looks good on mobile
- [ ] Related issues linked using `fixes #number`

2022-08-24 07:21 UTC, andrijunaedi commented
@Nunuyy tambahin screenshoot perubahannya dan coba kasih deskripsi singkat perubahannya apa aja

2022-08-24 07:22 UTC, andrijunaedi commented
@Nunuyy related issues nya diisi juga

2022-08-24 07:27 UTC, andrijunaedi commented on src/components/Solution/index.tsx
> +  ]
Data ini bisa dipindahkan ke folder json 

Ref: https://github.com/sawala-tech/sawala.tech/blob/main/src/components/Client/index.tsx#L38

2022-08-24 07:29 UTC, andrijunaedi commented on src/components/Solution/index.tsx
> +import Image from 'next/image'
Urutan import dari package ke components

```ts 
import Image from 'next/image'
import { Element } from 'react-scroll'
import tw, { styled } from 'twin.macro'

import { Container } from '@/components/Layouts'
```

2022-08-24 07:34 UTC, andrijunaedi commented on src/components/Solution/index.tsx
> +                  <Image src={`${item.icon}`} alt="" width={49} height={45}></Image>
Image ini gak balance 1:1 jadi agak penyok

![image](https://user-images.githubusercontent.com/73779893/186358507-2188c000-6009-47cc-83e8-b2c59db6056f.png)

Mungkin dari a @aldycavalera atau @wanfahdiva ada best practices nya

2022-08-24 07:36 UTC, andrijunaedi requested changes
Coba di fix dulu comments yang diatas @Nunuyy 

Thank you

2022-08-24 09:40 UTC, Nunuyy commented
Maaf a @andrijunaedi nunuy baru ngeuh sama comment-nya tadi malah lanjut ke cloud reseller hhe.. nanti malem nunuy langsung coba fix, makasihh

2022-08-27 15:27 UTC, Nunuyy commented on src/components/Solution/index.tsx
> +import Image from 'next/image'
a kenapa di section lain urutannya dari component ke package dulu ya?

2022-08-30 05:03 UTC, andrijunaedi commented on src/components/Solution/index.tsx
> +import Image from 'next/image'
Merujuk ke style guide ini https://github.com/airbnb/javascript#modules

2022-08-30 05:44 UTC, andrijunaedi requested changes

2022-08-30 05:44 UTC, andrijunaedi commented on src/components/Solution/index.tsx
> +                  <SolutionCard image={dataSolution.icon}></SolutionCard>
Title & SubTitle bisa dimasukan dalam component `SolutionCard`

Dimasukan sebagai props, kurang lebih jadi seperti ini untuk props nya:

![image](https://user-images.githubusercontent.com/73779893/187358631-a16b1de8-8a3a-4fdc-8e96-5095a3244700.png)

2022-08-30 06:02 UTC, andrijunaedi commented on src/components/Solution/index.tsx
> +                  <SolutionCard image={dataSolution.icon}></SolutionCard>
```tsx
{dataSolution.map(( [icon, title, subtitle] : [string, string, string ], i: number) => (
     <SolutionCard key={i} image={icon} title={title} subtitle={subtitle} />
))}
```

Ref: https://stackoverflow.com/a/65809274

2022-09-12 04:43 UTC, wanfahdiva approved these changes

2022-09-12 06:19 UTC, sutisnamulyana commented
- [ ] Copywriting updated nya cek di Figma gw minta Heri update

2022-09-18 14:11 UTC, closed without merging