feat: add sections our team
sawala-tech/sawala.tech pull request #23
Opened 2022-09-12 04:09 UTC by Nunuyy

Added a solutions section that explains what solutions are available at Sawala tech

## Changes
- Add Sections OurTeam #18 

## Screenshoots

- Sections OurTeam
![2022-9-12 0-6-29](https://user-images.githubusercontent.com/108647899/189540053-8f40c66a-850b-4648-869e-12a912a1c089.jpg)

- Responsive

| Mobile            | Tablet            |
| ------------- | ------------- |
| ![2022-9-11 23-45-3](https://user-images.githubusercontent.com/108647899/189539641-c93201b6-d760-47ae-a558-782dfeeda7af.png) | ![2022-9-11 23-58-30](https://user-images.githubusercontent.com/108647899/189539736-a1b94131-1b2d-4f8a-82b7-37cc4ac40b2a.png) |

## Checklist
- [ ] Copywriting 
- [ ] Requires dependency update?
- [ ] Automated tests
- [ ] Looks good on large screens
- [ ] Looks good on mobile
- [ ] Related issues linked using fixes #18

2022-09-12 04:39 UTC, wanfahdiva requested changes

2022-09-12 04:39 UTC, wanfahdiva commented on src/components/Card/Founder/index.tsx
> +  ${tw`place-items-center items-center pl-5 my-auto flex w-full h-[220px] cursor-default transition ease-in-out delay-100 focus:outline-none hover:scale-110 hover:bg-primary hover:bg-opacity-10 durat
```suggestion
  ${tw`place-items-center items-center pl-5 my-auto flex w-full h-[170px] md:h-[220px] cursor-default transition ease-in-out delay-100 focus:outline-none hover:scale-110 hover:bg-primary hover:bg-opacity-10 duration-200 bg-gray-50 rounded-xl`}
```

2022-09-12 04:39 UTC, wanfahdiva commented on src/components/Card/Founder/index.tsx
> +  ${tw`text-base font-medium text-gray-500 pb-7`}
```suggestion
  ${tw`text-base font-medium text-gray-500 pb-5 md:pb-7`}
```

2022-09-12 04:39 UTC, wanfahdiva commented on src/components/Card/Team/index.tsx
> +  ${tw`pl-5 flex w-full h-[220px] cursor-default transition ease-in-out delay-100 focus:outline-none hover:scale-110 hover:bg-primary hover:bg-opacity-10 duration-200 bg-gray-50 rounded-xl place-item
```suggestion
  ${tw`pl-5 flex w-full h-[170px] md:h-[220px] cursor-default transition ease-in-out delay-100 focus:outline-none hover:scale-110 hover:bg-primary hover:bg-opacity-10 duration-200 bg-gray-50 rounded-xl place-items-center`}
```

2022-09-12 04:39 UTC, wanfahdiva commented on src/components/Card/Team/index.tsx
> +  ${tw`text-base font-medium text-gray-500 pb-7`}
```suggestion
  ${tw`text-base font-medium text-gray-500 pb-5 md:pb-7`}
```

2022-09-12 06:18 UTC, sutisnamulyana commented
- [ ] Typo: Lead Develover -->Lead Developer
- [ ] Semua tidak pake gelar academic
- [ ] Link linkedin dibikin new tab

2022-09-18 02:34 UTC, sutisnamulyana approved these changes
Good to go

2022-09-18 15:23 UTC, closed without merging